/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundContainer: typeof import('./src/components/BackgroundContainer.vue')['default']
    DesktopContainer: typeof import('./src/components/DesktopContainer.vue')['default']
    DividerHorizontal: typeof import('./src/components/DividerHorizontal.vue')['default']
    DividerVertical: typeof import('./src/components/DividerVertical.vue')['default']
    EarthScene: typeof import('./src/components/custom/EarthScene.vue')['default']
    EarthWindowContent: typeof import('./src/components/window/EarthWindowContent.vue')['default']
    ImageViewerWindowContent: typeof import('./src/components/window/ImageViewerWindowContent.vue')['default']
    'ITablerBrand-': typeof import('~icons/tabler/brand-')['default']
    ITablerBrandBluesky: typeof import('~icons/tabler/brand-bluesky')['default']
    ITablerBrandGithub: typeof import('~icons/tabler/brand-github')['default']
    ITablerBrandMastodon: typeof import('~icons/tabler/brand-mastodon')['default']
    ITablerBrandSoundcloud: typeof import('~icons/tabler/brand-soundcloud')['default']
    ITablerLink: typeof import('~icons/tabler/link')['default']
    ITablerPlayerPauseFilled: typeof import('~icons/tabler/player-pause-filled')['default']
    ITablerPlayerPlayFilled: typeof import('~icons/tabler/player-play-filled')['default']
    ITablerPlayerStopFilled: typeof import('~icons/tabler/player-stop-filled')['default']
    ITablerVolume: typeof import('~icons/tabler/volume')['default']
    MSDOSPromptWindowContent: typeof import('./src/components/window/MSDOSPromptWindowContent.vue')['default']
    RunWindowContent: typeof import('./src/components/window/RunWindowContent.vue')['default']
    SocialDesktopIcons: typeof import('./src/components/SocialDesktopIcons.vue')['default']
    SocialLinksWindowContent: typeof import('./src/components/window/SocialLinksWindowContent.vue')['default']
    SolitaireMadness: typeof import('./src/components/custom/SolitaireMadness.vue')['default']
    Starscape: typeof import('./src/components/custom/Starscape.vue')['default']
    ToolbarContainer: typeof import('./src/components/ToolbarContainer.vue')['default']
    ToolbarInfo: typeof import('./src/components/ToolbarInfo.vue')['default']
    ToolbarOpenWindowButton: typeof import('./src/components/ToolbarOpenWindowButton.vue')['default']
    ToolbarStartButton: typeof import('./src/components/ToolbarStartButton.vue')['default']
    ToolbarStartMenu: typeof import('./src/components/ToolbarStartMenu.vue')['default']
    ToolbarStartMenuListItem: typeof import('./src/components/ToolbarStartMenuListItem.vue')['default']
    ToolbarStartMenuSubMenu: typeof import('./src/components/ToolbarStartMenuSubMenu.vue')['default']
    ToolbarStartMenuSubMenuItem: typeof import('./src/components/ToolbarStartMenuSubMenuItem.vue')['default']
    VirusPopUpContent: typeof import('./src/components/window/VirusPopUpContent.vue')['default']
    WelcomeWindowContent: typeof import('./src/components/window/WelcomeWindowContent.vue')['default']
    Win98Icon: typeof import('./src/components/base/Win98Icon.vue')['default']
    Win98IconContainer: typeof import('./src/components/base/Win98IconContainer.vue')['default']
    Win98Window: typeof import('./src/components/base/Win98Window.vue')['default']
    WindowsMediaPlayerWindowContent: typeof import('./src/components/window/WindowsMediaPlayerWindowContent.vue')['default']
  }
}
