name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/hugo-setup
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.12
      with:
        hugo-version: '0.74.2'
        extended: true
